name: store_finder
description: A store finder app with local database using Provider State Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  provider: ^6.0.5
  sembast: ^3.4.4
  sembast_web: ^2.1.3
  geolocator: ^9.0.2
  http: ^0.13.6
  path_provider: ^2.0.15
  path: ^1.8.3
  cupertino_icons: ^1.0.5
  vector_math: ^2.1.4
  maps_toolkit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
